import error
import io

try {
  ''.this_is_intentional ; Will trigger an exception.
} catch e {
  io.fprintln(io.ERROR, e)
}

try {
  raise error.Error('This is intentional!')
} catch e {
  io.fprintln(io.ERROR, e)
}